add location cache
openimis/openimis-be-location_py pull request #142
Opened 2024-10-16 09:54 UTC by delcroip

2024-10-18 16:28 UTC, weilu requested changes
@delcroip can you briefly describe the intention of this change set in the PR description?

Additionally, I feel uneasy with such extensive changes with minimal tests coverage. I would really urge you to add tests to ensure the existing logic is not affected and the newly added functionalities are well covered.

2024-10-18 16:28 UTC, weilu commented on location/models.py
> +    free_cache_for_user('*')
I don't think wildcard is supported natively in django cache. I also don't see wildcard logic implemented in the function. @delcroip you sure this will work?

2024-10-20 19:25 UTC, delcroip commented on location/models.py
> +    free_cache_for_user('*')
I will add redis as cache but once I am sure this works, I will make some  cache invalidation test

2024-10-21 10:48 UTC, delcroip commented on location/models.py
> +    free_cache_for_user('*')
test added and support of wildcard managed

2024-10-22 13:59 UTC, merged