OP-946: Check and graphql query - unique location code.
openimis/openimis-be-location_py pull request #47
Opened 2023-01-04 12:33 UTC by wzglinieckisoldevelo

Ticket: https://openimis.atlassian.net/browse/OP-946

FE PR: https://github.com/openimis/openimis-fe-location_js/pull/32

Changes:
- Added BE check for validating location code.
- Added graphql query for checking uniqueness of location code

2023-01-09 11:40 UTC, dborowiecki requested changes
Please find my comments and align code with changes introduced in [OP-948](https://github.com/openimis/openimis-be-location_py/pull/44/files)

2023-01-10 12:06 UTC, delcroip commented on location/schema.py
> +
```suggestion
            return bool(errors)
```

2023-01-10 12:08 UTC, delcroip commented on location/schema.py
> +
```suggestion
        return False if errors else True

```

2023-01-10 14:08 UTC, dborowiecki approved these changes
Looks good.

2023-01-10 14:08 UTC, merged