OTC-950: District dropdown under FSP displays only mapped district of the logged in user
openimis/openimis-be-location_py pull request #55
Opened 2023-03-10 14:39 UTC by hirensoni913

Filter 'ne' added in name and code, The reason for this change is to exclude any district without a parent. 
https://openimis.atlassian.net/browse/OTC-950

2023-03-13 08:28 UTC, delcroip commented
See CI, NotEqual not insstalled

2023-05-18 10:04 UTC, jdolkowski commented on location/schema.py
> +              dist = UserDistrict.get_user_districts(info.context.user._u)
@delcroip I was being consistent with other pieces of code. If you search for **if settings.ROW_SECURITY:** it is implemented like that throughout the whole project.

2023-05-22 16:17 UTC, dragos-dobre requested changes

2023-05-22 16:17 UTC, dragos-dobre commented on location/gql_queries.py
> +from core.custom_lookups import *
Do we need to import *?

2023-05-23 08:09 UTC, jdolkowski commented on location/gql_queries.py
> +from core.custom_lookups import *
no we don't, i removed that

2023-05-24 08:00 UTC, dragos-dobre approved these changes

2023-05-24 08:00 UTC, merged